### ISSUE TITLE
Great work. Could you please solve this problem I have encountered?

### ISSUE THREAD

**Issue by Githubsatan** [pengbo-learn/python-face-relighting#2]
No such file or directory:
 'python-face-relighting/weights/mobilenet0.25_Final.pth'

The code is as follows：
![issue](https://user-images.githubusercontent.com/38398115/71949485-a6f18b00-320e-11ea-86c6-29df8cb968db.png)

**Comment by pengbo-learn** [comment]
Download the model weight from https://github.com/biubug6/Pytorch_Retinaface/tree/d2ada8295ab9c3e12145dae5b18465ad1c5f223f

**Comment by pengbo-learn** [comment]
> No such file or directory:
> 'python-face-relighting/weights/mobilenet0.25_Final.pth'
> 
> The code is as follows：
> ![issue](https://user-images.githubusercontent.com/38398115/71949485-a6f18b00-320e-11ea-86c6-29df8cb968db.png)

Download the model weight from https://github.com/biubug6/Pytorch_Retinaface/tree/d2ada8295ab9c3e12145dae5b18465ad1c5f223f
