### ISSUE TITLE
Trasferring light only 

### ISSUE THREAD

**Issue by ParnianA** [pengbo-learn/python-face-relighting#5]
Hello,

Thanks for sharing. Can I use this code to transfer light only and not the color as stated in the original paper?

**Comment by pengbo-learn** [comment]
> Hello,
> 
> Thanks for sharing. Can I use this code to transfer light only and not the color as stated in the original paper?

which line in the paper?

**Comment by pengbo-learn** [comment]
> Hello,
> 
> Thanks for sharing. Can I use this code to transfer light only and not the color as stated in the original paper?

I missed the point. Now relighting without color is integrated in the latest commit.
